class AppException(Exception): ...


class DbError(AppException): ...


class DbConnectionError(AppException): ...


class DbIncorrectData(AppException): ...


class UserNotExist(AppException): ...


class UserAlreadyExist(AppException): ...


class InvalidCredentials(AppException): ...


class InvalidToken(AppException): ...


class TokenExpire(AppException): ...
