"""add_event_picture

Revision ID: 4a409af02efb
Revises: a40047626bbf
Create Date: 2026-03-17 22:03:27.834688

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a409af02efb"
down_revision: Union[str, Sequence[str], None] = "a40047626bbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("picture_url", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "picture_url")
    # ### end Alembic commands ###
