"""add_event_owner

Revision ID: 92d58bf31542
Revises: 4a409af02efb
Create Date: 2026-04-28 23:18:21.923757

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from config import settings

# revision identifiers, used by Alembic.
revision: str = "92d58bf31542"
down_revision: Union[str, Sequence[str], None] = "4a409af02efb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    result = conn.scalars(sa.text("SELECT id FROM users LIMIT 1;"))
    user_id = result.one_or_none()
    if user_id is None:
        user_id = conn.scalar(
            sa.text(
                "INSERT INTO users (username, role, email, password) "
                "VALUES ('user', 'user', 'user@example.com', :password) RETURNING id;"
            ),
            {"password": settings.ADMIN_PASSWORD},
        )
    op.add_column(
        "events",
        sa.Column(
            "owner_id", sa.Integer(), nullable=False, server_default=str(user_id)
        ),
    )
    op.alter_column("events", "owner_id", server_default=None)
    op.create_foreign_key(
        op.f("fk_events_owner_id_users"), "events", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_events_owner_id_users"), "events", type_="foreignkey")
    op.drop_column("events", "owner_id")
    # ### end Alembic commands ###
